




.build/atmega8/src/essai_moteur.cpp : src/essai_moteur.ino
	@mkdir -p .build/atmega8/src
	@echo [93msrc/essai_moteur.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/atmega8/src/essai_moteur.cpp
	@true

